<?php
/**
 * Точка входа в шаблон Demolancer.
 *
 * В шаблоне используется:
 *   - Кастомное расширение PHP-шаблонизатора `DemolancerPhpExtension`
 *   - Кастомный файл config.ini
 *   - Сборщик css и js-ресурсов gulp, @see gulpfile.js
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemolancerPhpExtension $this
 * @var array $variables
 */

$this->initializeCommonVariables($variables);
?>
<?= $this->render($variables, 'layout/index') ?>
