<?php
/**
 * Контент страницы модуля "Структура"
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemolancerPhpExtension $this
 * @var array $variables
 */
?>
<?php if ($this->isHomePage($variables)): ?>
	<?= $this->render($variables, 'content/home') ?>
<?php elseif ($this->is404Page($variables)): ?>
	<?= $this->render($variables, 'content/notfound') ?>
<?php else: ?>
	<?= $this->render($variables, 'content/common') ?>
<?php endif; ?>
