<?php
/**
 * Меню в шапке сайта
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemolancerPhpExtension $this
 * @var array $variables
 */
$variables['level'] = 0;
?>
<button type="button" class="btn btn-umi-shop b-navbar" data-toggle="collapse" data-target=".nav-collapse">
	<?= $this->escape($this->translate('mobile_menu_label')) ?>
</button>
<div class="nav-collapse collapse">
	<?= $this->render($variables, 'content/menu_item_list') ?>
</div>

