<?php
/**
 * Контент 404ой страницы
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemolancerPhpExtension $this
 * @var array $variables
 */
$setting = $this->getSettingsContainer();
$id =  $this->escape($setting->getId());
?>
<div class="container">
	<?= $this->render($this->macros('core', 'navibar'), 'core/navibar') ?>
	<div class="row-fluid umi-second-content">
		<h1 id="page_main_header" class="h1">
			<span class="h1_content" umi:object-id="<?= $id ?>" umi:field-name="404_header"
				  umi:empty="<?= $this->escape($this->translate('empty_page_h1')) ?>"><?= $this->escape($setting->getValue('404_header')) ?></span>
		</h1>
		<div class="text" umi:object-id="<?= $id ?>" umi:field-name="404_content"
			 umi:empty="<?= $this->escape($this->translate('empty_page_content')) ?>"><?= $setting->getValue('404_content') ?></div>
		<div class="text sitemap">
			<?= $this->render($this->macros('content', 'sitemap'), 'content/sitemap') ?>
		</div>
		<div class="seo_text text" umi:object-id="<?= $id ?>" umi:field-name="404_additional_content"
			 umi:empty="<?= $this->escape($this->translate('empty_additional_content')) ?>">
			<?= $setting->getValue('404_additional_content'); ?>
		</div>
	</div>
</div>
