<?php
/**
 * Хлебные крошки
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemolancerPhpExtension $this
 * @var array $variables
 */
$breadcrumbList = isset($variables['items']) ? $variables['items'] : [];
$breadcrumbList = $this->prepareBreadcrumbs($breadcrumbList);
?>
<div class="row-fluid umi-breadcrumb">
	<div class="span12">
		<div class="breadcrumbs">
			<?= $this->render($breadcrumbList, 'core/breadcrumb_list') ?>
		</div>
	</div>
</div>
