<?php
/**
 * Список ошибок макросов (когда url содержит get-параметр `_err`).
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemolancerPhpExtension $this
 * @var array $variables
 */
?>
<?php if (isset($variables['items'])): ?>
	<div class="container">
		<div class="text system_errors">
			<h3>
				<?= $this->translate('js-error-occurred') ?>
			</h3>
			<ul>
				<?php foreach ($variables['items'] as $error): ?>
					<?= $this->render($error, 'system/error_list_item') ?>
				<?php endforeach; ?>
			</ul>
		</div>
	</div>
<?php endif; ?>
