<?php
/**
 * Блог
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemolancerPhpExtension $this
 * @var array $variables
 * @var iUmiHierarchyElement $page
 */
$page = $this->getPageAndPushToEditable($variables['pageId']);
$id = $this->escape($page->getId());
?>
<div class="container">
	<?= $this->render($this->macros('core', 'navibar'), 'core/navibar') ?>
	<div class="row-fluid umi-second-content">
		<h1 id="page_main_header" class="h1">
			<span class="h1_content" umi:element-id="<?= $id ?>" umi:field-name="h1"
				  umi:empty="<?= $this->escape($this->translate('empty_page_h1')) ?>"><?= $this->escape($page->getValue('h1')) ?></span>
		</h1>
		<div class="seo_text text" umi:element-id="<?= $id ?>" umi:field-name="description"
			 umi:empty="<?= $this->escape($this->translate('empty_page_content')) ?>">
			<?= $page->getValue('description') ?>
		</div>
		<?= $this->render($this->macros('blogs20', 'postsList', [$id]), 'blogs20/post_list') ?>
		<div class="cleaner"></div>
		<div class="seo_text text" umi:element-id="<?= $id ?>" umi:field-name="additional_content"
			 umi:empty="<?= $this->escape($this->translate('empty_additional_content')) ?>">
			<?= $page->getValue('additional_content'); ?>
		</div>
	</div>
</div>
