<?php
/**
 * Список постов с заданным тегом
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemolancerPhpExtension $this
 * @var array $variables
 */
$settings = $this->getSettingsContainer();
$id = $this->escape($settings->getId());
$tag = ltrim(UmiCms\Service::Request()->getPath(), 'blogs20/postsByTag/');
$variables = $this->macros('blogs20', 'postsByTag', [$tag]);
$postList = isset($variables['items']) ? $variables['items'] : [];
?>
<div class="container">
	<?= $this->render($this->macros('core', 'navibar'), 'core/navibar') ?>
	<div class="row-fluid umi-second-content">
		<h1 id="page_main_header" class="h1">
			<span class="h1_content">
				<span class="h1_content" umi:object-id="<?= $id ?>" umi:field-name="post_by_tag_header"
					  umi:empty="<?= $this->escape($this->translate('empty_page_h1')) ?>">
					<?= $this->escape($settings->getValue('post_by_tag_header')) ?>
				</span>
				"<?= $this->escape($tag) ?>"
			</span>
		</h1>
		<div class="seo_text text" umi:object-id="<?= $id ?>" umi:field-name="post_by_tag_main_content"
			 umi:empty="<?= $this->escape($this->translate('empty_page_content')) ?>">
			<?= $settings->getValue('post_by_tag_main_content') ?>
		</div>
		<div class="blog">
			<?php foreach ($postList as $post): ?>
				<?= $this->render($post, 'blogs20/post_list_item') ?>
			<?php endforeach; ?>
		</div>
		<?= $this->render($this->macros('system', 'numpages', [$variables['total'], $variables['per_page']]), 'system/numpages') ?>
		<div class="cleaner"></div>
		<div class="seo_text text" umi:object-id="<?= $id ?>" umi:field-name="post_by_tag_additional_content"
			 umi:empty="<?= $this->escape($this->translate('empty_additional_content')) ?>">
			<?= $settings->getValue('post_by_tag_additional_content'); ?>
		</div>
	</div>
</div>
